import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import "@/style/globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
         <div className="content-container">{children}</div>
        <Footer />
 <ToastContainer />
      </body>
   
    </html>
    
  );
}
